# 1. Import the necessary libraries for you to be able to query 4square API

In [1]:
import requests
import json
import pandas as pd
from getpass import getpass

# 2. Get names and location of the 10 coffee places by passing Ironhack as your location

In [2]:
api_key = getpass()

In [3]:
url = "https://api.foursquare.com/v3/places/search"
headers = {"accept": "application/json",
           "Authorization":api_key}
params = {
    "ll":"40.3906,-3.6989",
    "query":"coffee",
    "limit": 10}

response = requests.get(url, headers=headers, params=params)
#response.status_code
data = response.json()
results = data.get("results",[])

coffee_places = [{"Name":place.get("name"),
                  "Address": place.get("location", {}).get("formatted_address", "Address not available")
                                       }
                                       for place in results]
df = pd.DataFrame(coffee_places)
df

,Name,Address
0,Cantina Matadero,"P. de la Chopera, 14, 28045 Madrid Comunidad d..."
1,El Gallo de Oro,"Antonio López, 113, 28026 Madrid Comunidad de ..."
2,Dot Café Bar,"Calle de Eugenio Sellés, 6, 28045 Madrid Comun..."
3,Cafetería Churrería Legazpi,"Plaza Legazpi, 3, 28045 Madrid Comunidad de Ma..."
4,Viena Capellanes,"P.º Molino, 6 (C. Frigiliana), 28045 Madrid Co..."
5,Salon de Te al Yabal,"Cáceres, 52 (P. Santa María de la Cabeza), 280..."
6,BBIG Delice Café,"Calle Juan de Vera, 11, 28045 Madrid Comunidad..."
7,Trasmontana,"Calle Bolivar, 18, 28045 Madrid Comunidad de M..."
8,Heladeria Venezzia,"Paseo de las Delicias, 102 (C. Divino Vallés),..."
9,Sanpas Cafetería Restaurante,"Calle Plomo, 1 (C. Antracita), 28045 Madrid Co..."

# 3. Now get the 5 CLOSEST coffe places. Make use of params: limit, near?

In [4]:
params = {
    "near":"Paseo de la Chopera, 14, 28045, Madrid",
    "query":"coffee",
    "limit": 5}

response = requests.get(url, headers=headers, params=params)
#response.status_code
data = response.json()
results = data.get("results",[])

coffee_places = [{"Name":place.get("name"),
                  "Address": place.get("location", {}).get("formatted_address", "Address not available")
                                       }
                                       for place in results]
df = pd.DataFrame(coffee_places)
df

,Name,Address
0,El Jardín de Salvador Bachiller,"Calle Montera, 37, 28013 Madrid Comunidad de M..."
1,La Rollerie,"Calle Atocha, 20, 28012 Madrid Comunidad de Ma..."
2,El Riojano,"Calle Mayor, 10, 28013 Madrid Comunidad de Madrid"
3,Chocolatería San Ginés,"Pasadizo de San Ginés, 5 (C. Arenal), 28013 Ma..."
4,La Rollerie,"Calle Mayor, 24 (Coloreros 3), 28013 Madrid Co..."

# 4. Define a function that returns name, lat, long for starbucks OR restaurants AND for any given location

In [5]:
def foursquare_places (api_key, location, query="Starbucks, restaurant", limit =10):
    url = "https://api.foursquare.com/v3/places/search"
    headers = {"accept": "application/json",
           "Authorization":api_key}
    params = {
        "near":location,
        "query":query,
        "limit": limit}
    
    response=requests.get(url, headers=headers, params=params)

    if response.status_code !=200:
        print("Request failed:", response.status_code)

    data = response.json()
    results=data.get("results", [])

    places = [
        {
            "name": place["name"],
            "lat" :place["geocodes"]["main"]["latitude"],
            "lng" :place["geocodes"]["main"]["longitude"]
        }
        for place in results
    ]
    return places

# 5. Export it into data folder as a json: `data/coffe_shops.json`

In [ ]:
import json
import os

In [ ]:
os.makedirs("data", exist_ok=True)

In [ ]:
with open("data/placed.json")

# BONUS: load it into MongoDB in a collection named "ironcoffee" using pymongo

In [7]:
# your code here